language: cpp

compiler:
  - gcc-4.8

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - zip
      - zlib1g-dev

before_install:
  - which gcc
  - gcc --version
  - make --version
  - cmake --version
  - automake --version
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.1.2/bazel-0.1.2-installer-linux-x86_64.sh'
  - chmod +x bazel-0.1.2-installer-linux-x86_64.sh
  - ./bazel-0.1.2-installer-linux-x86_64.sh --user
  - cat ~/.bazelrc >> .bazelrc

script: 
  - bazel test --config=travis //src/...
